[package]
name = "xmlgenerator"
version = "0.1.0"
edition = "2024"

[dependencies]
xsd-parser = "1.2.0"
xml-builder = "0.5.4"
fake = "4.3.0"
rand = "0.9.2"
rand_regex = "0.18.1"
rand_xorshift = "0.4.0"

[dev-dependencies]
workspace_root = "0.1.2"
