[build-system]
requires = ["maturin>=1.10.2,<2.0"]
build-backend = "maturin"

[project]
name = "pyxmlgenerator"
description = "Python bindings for the Rust XMLGenerator library"
requires-python = ">=3.10"
readme = "../README.md"
authors = [{ name = "Z M Williams", email = "z.m.will@icloud.com" }]
keywords = ["XML", "Testing"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "pyxsdtestdata",
    "xmlschema",
    "lxml",
]
