<?xml version="1.0" encoding="UTF-8"?>

<!--
Root element contains reference to Head element
-->

<xsd:schema
        xmlns="https://www.example.com/Namespace"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.example.com/Namespace"
>

    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Head"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Head" type="HeadType"/>

    <xsd:complexType name="HeadType">
        <xsd:sequence>
            <xsd:element name="Ear"/>
            <xsd:element name="Eye"/>
            <xsd:element name="Mouth"/>
            <xsd:element name="Nose"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>
