[workspace]
resolver = "3"
members = [
    "py_xml_generator",
    "py_xsd_test_data",
    "reader",
    "regex_translator",
    "xml_generator",
    "xsd_test_data",
    "xsd_validator",
]
default-members = ["xsd_validator", "regex_translator", "xml_generator"]

[workspace.package]
version = "0.2.3"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/zwill22/xmlgenerator"
categories = ["development-tools", "development-tools::testing"]
description = "Generate XML instances from an XML Schema (XSD)"
keywords = ["XML", "XSD", "Testing", "Validation", "Generator", "Generation"]


[workspace.dependencies]
file_to_string = { path = "reader", version = "0.2.3" }
xsdtestdata = { path = "xsd_test_data", version = "0.2.3" }
xsdvalidator = { path = "xsd_validator", version = "0.2.3" }
regextranslator = { path = "regex_translator", version = "0.2.3" }
xmlgenerator = { path = "xml_generator", version = "0.2.3" }
pyxsdtestdata = { path = "py_xsd_test_data", version = "0.2.3" }
