[project]
name = "schema2xml"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.4.2",
    "lxml>=6.0.0",
    "requests>=2.32.4",
]
