[package]
name = "xsdtestdata"
categories.workspace = true
description.workspace = "XSD Test data manaager"
edition.workspace = true
keywords.workspace = ["Testing", "Test data", "XSD", "Database"]
license-file.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
file_to_string = { workspace = true }
reqwest = { version = "0.12.24", features = ["blocking"] }
roxmltree = "0.21.1"
zip = "6.0.0"

[dev-dependencies]
workspace_root = "0.2.0"
