[package]
name = "xsdtestdata"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
roxmltree = "0.21.1"
reqwest = { version = "0.12.24", features = ["blocking"] }
zip = "6.0.0"
file_to_string = { workspace = true }

[dev-dependencies]
workspace_root = "0.2.0"
