[package]
name = "xsdtestdata"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
roxmltree = "0.20"
reqwest = "0.12"
futures = "0.3"
zip = "4.6"
workspace_root = "0.2"
encoding_rs = "0.8"
encoding_rs_io = "0.1"