//! The XSDValidator crate provides methods for validating XSD files
//!
//! The crate uses [rust bindings] for the [libxml2] C library to check whether an XSD file is valid.
//! It also checks whether the XSD contains any infinite loops using the [tracker::Tracker] struct.
//! All relevant functionality is provided in the [XSDValidator] struct, which manages the [libxml2] interface.
//!
//! [rust bindings]: https://github.com/zwill22/libxml2-rs
//! [libxml2]: https://gitlab.gnome.org/GNOME/libxml2
//!
//!
pub use crate::error::XSDValidationError;
use crate::parser::Parser;
use crate::recursion::recursion_check;
use gag::Gag;
use libxml2_rs::{xmlCleanupParser, xmlInitParser};
use std::env::{current_dir, set_current_dir};
use std::path::PathBuf;
use std::sync::Mutex;

mod error;
mod parser;
mod recursion;
mod schema;
pub mod tracker;

/// Struct needed for validating XSD files by providing an interface to [libxml2-rs]
///
/// The struct manages the [libxml2] functionality and uses it to validate XSD files.
/// The struct should only be initialised once using [XSDValidator::new], since the
/// initialiser calls the unsafe C function `xmlInitParser()` which initialises the
/// [libxml2] parser globally and should not be called more than once before calling
/// the `xmlCleanupParser()` function in the destructor.
///
/// [libxml2-rs]: https://github.com/zwill22/libxml2-rs
///
/// # Fields
///
/// - `lock` (`Mutex<()>`) - Describe this field.
/// - `warnings` (`bool`) - Describe this field.
///
/// # Example
///
/// ```rust
/// use std::path::PathBuf;
/// use xsdvalidator::XSDValidator;
///
/// fn validate_file(path: &PathBuf) {
///     let validator = XSDValidator::new(true);
///     
///     let valid = match validator.validate(path) {
///         Ok(v) => v,
///         Err(e) => {
///             eprintln!("Error validating file: {}", path.display());
///             return;
///         },
///     };
///
///     if valid {
///         println!("Valid file: {}", path.display());
///     } else {
///         println!("Invalid file: {}", path.display());
///     }
/// }
/// ```
pub struct XSDValidator {
    lock: Mutex<()>,
    warnings: bool,
}

impl XSDValidator {
    /// Generate a new [XSDValidator] object
    ///
    /// This function constructs a new [XSDValidator] instance.
    /// It calls the [libxml2] function `xmlInitParser()`, which initialises the parser globally.
    /// This function should not be initialised without first calling `xmlCleanupParser()` in the destructor.
    /// As a result, once one instance of the class should exist at any one time.
    /// Initialising multiple [XSDValidator] objects results in undefined behaviour.
    ///
    /// # Arguments
    ///
    /// - `print_warnings` (`bool`) - Print warnings generated by [libxml2]
    ///
    /// # Returns
    ///
    /// - [XSDValidator] - An validator object
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use xsdvalidator::{XSDValidator, XSDValidationError};
    ///
    /// fn validate_files(files: &[PathBuf]) -> Result<(), XSDValidationError> {
    ///     let validator = XSDValidator::new(true);
    ///     
    ///     for file in files {
    ///         let valid = validator.validate(file)?;
    ///         if !valid {
    ///             println!("Invalid file: {}", file.display());
    ///         }
    ///     }
    ///
    ///     Ok(())
    /// }
    /// ```
    pub fn new(print_warnings: bool) -> XSDValidator {
        unsafe {
            xmlInitParser();
        }

        XSDValidator {
            lock: Mutex::new(()),
            warnings: print_warnings,
        }
    }

    // TODO New XSDValidator
    fn validate_file(&self, path: &PathBuf) -> Result<bool, XSDValidationError> {
        let _guard = self.lock.lock().unwrap();
        recursion_check(path)?;
        let mut errors: Vec<String> = Vec::new();

        let parser = Parser::new(path)?;
        parser.setup_error_handler(&mut errors);

        let valid = match self.warnings {
            true => parser.parse(),
            false => {
                let _gag = Gag::stderr().ok();

                parser.parse()
            }
        };

        for error in &errors {
            if error.to_lowercase().contains("skipping") {
                if self.warnings {
                    eprintln!("{}", error);
                }
            } else {
                return Err(XSDValidationError::ParseError(error.clone()));
            }
        }

        Ok(valid)
    }

    /// Validation method for [XSDValidator]
    ///
    /// Main validation method for the [XSDValidator], it uses [libxml2-rs] to validate the input file.
    /// Additionally, it check for recursive elements in the schema that would result in infinite loops.
    /// Since this is the only additional check performed, the definition of a valid XSD file is inherited from [libxml2].
    /// Therefore, if [libxml2] thinks a file is valid, then [XSDValidator] should as well (and vice versa).
    ///
    /// The method returns a boolean describing whether a file is valid or not.
    /// However, if it encounters an error, it will return an [XSDValidationError].
    /// Some of these errors can be interpreted as an invalid XSD file.
    ///
    /// # Arguments
    ///
    /// - `path` (`&PathBuf`) - Path to an XML Schema (XSD) file
    ///
    /// # Returns
    ///
    /// - `Result<bool, XSDValidationError>` - Whether the input file is valid or not.
    ///
    /// # Errors
    ///
    /// - [XSDValidationError::PathError] - Invalid file path provided or file does not exist
    /// - [XSDValidationError::LibXML2InterfaceError] - Error interfacing with [libxml2-rs]
    /// - [XSDValidationError::OutputRedirectError] - Error redirecting [libxml2] warnings
    /// - [XSDValidationError::ParseError] - Error from RoXMLTree parser
    /// - [XSDValidationError::ReadFileError] - Error reading file with [file_to_string]
    /// - [XSDValidationError::XSDRecursionError] - Recursion found in XSD file
    ///
    /// # Examples
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use xsdvalidator::XSDValidator;
    ///
    /// fn validate_file(path: &PathBuf) {
    ///     let validator = XSDValidator::new(true);
    ///     
    ///     let valid = match validator.validate(path) {
    ///         Ok(v) => v,
    ///         Err(e) => {
    ///             eprintln!("Error validating file: {}", path.display());
    ///             return;
    ///         },
    ///     };
    ///
    ///     if valid {
    ///         println!("Valid file: {}", path.display());
    ///     } else {
    ///         println!("Invalid file: {}", path.display());
    ///     }
    /// }
    /// ```
    pub fn validate(&self, path: &PathBuf) -> Result<bool, XSDValidationError> {
        let wd = current_dir().expect("current_dir() failed");
        let file_dir = match path.parent() {
            Some(parent) => parent,
            None => {
                return Err(XSDValidationError::PathError);
            }
        };

        set_current_dir(file_dir).expect("set_current_dir() failed");

        let result = self.validate_file(path);

        set_current_dir(wd).expect("set_current_dir() failed");

        result
    }
}

/// Destructor for [XSDValidator]
///
/// This is necessary to call `xmlCleanupParser()` from [libxml2].
/// This is the opposite of the `xmlInitParser()` function in the constructor,
/// and should always be called before `xmlInitParser()` is called a second time.
///
impl Drop for XSDValidator {
    fn drop(&mut self) {
        unsafe { xmlCleanupParser() }
    }
}
