[package]
name = "xsdvalidator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libxml2-rs = { git = "https://github.com/zwill22/libxml2-rs.git" }
futures = "0.3.31"
libc = "0.2.175"
roxmltree = "0.20"

[dev-dependencies]
workspace_root = "0.2.0"
xsdtestdata = { workspace = true }
