[package]
name = "pyxsdtestdata"
categories.workspace = true
description = "XSD test data"
edition.workspace = true
keywords = ["XSD", "Testing", "Test", "Data", "Validation"]
license-file.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "pyxsdtestdata"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.1", features = ["abi3-py310"] }
xsdtestdata = { workspace = true }
