[package]
name = "regextranslator"
categories.workspace = true
description = "Translator for XSD patterns into Rust-style Regular Expressions"
edition.workspace = true
keywords = [
    "Pattern",
    "Rust",
    "XSD",
    "Regex",
    "Translator",
]
license-file.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
line-ending = "1.5.1"
regex = "1.12.2"
regexml = "0.2.1"
unic-char-basics = "0.9.0"
unic-ucd = "0.9.0"
unic-ucd-block = "0.9.0"
unic-ucd-category = "0.9.0"

[dev-dependencies]
file_to_string = { workspace = true }
roxmltree = "0.21.1"
rstest = "0.26.1"
workspace_root = "0.2.0"
xsdtestdata = { workspace = true }
