name: XMLGenerator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
    - uses: actions/checkout@v4

    - name: Summary
      id: strings
      shell: bash
      run: |
        echo "Operating system=${{matrix.os}}"
        echo "Python Version=${{matrix.python-version}}"

    - name: Install uv and set python version
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{matrix.python-version}}

    - name: Setup project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest

    - name: Lint with ruff
      run: uv run ruff check

    - name: Get Coverage
      run: |
        source .venv/bin/activate
        coverage run -m pytest
        coverage xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
