name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: py_xml_generator

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Rust
        if: ${{ env.ACT }}
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Rust
        run: rustup show

      - name: Setup clang
        if: ${{ env.ACT }}
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest

      - name: Setup cmake
        if: ${{ env.ACT }}
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.22"

      - name: UV setup
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
          activate-environment: "true"

      - name: Install llvm cov
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Export Prefixes
        run: |
          . <(cargo llvm-cov show-env --sh)
          env >> $GITHUB_ENV
          echo CARGO_TARGET_DIR=$CARGO_LLVM_COV_TARGET_DIR >> $GITHUB_ENV
          echo CARGO_INCREMENTAL=1 >> $GITHUB_ENV

      - name: Setup UV Tests
        run: |
          uv sync --all-packages --all-groups

      - name: UV tests with coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage xml

      - name: Generate llvm cov report
        run: cargo llvm-cov report --lcov --output-path coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          