name: Test Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Rust
      if: ${{ env.ACT }}
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Rust
      run: rustup update

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
