name: Test Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: py_xml_generator

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - 3.9
          - 3.10
          - 3.11
          - 3.12
          - 3.13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Rust
        if: ${{ env.ACT }}
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Rust
        run: rustup show

      - name: UV setup
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: 'true'

      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev --active --no-install-package pyxmlgenerator
          uv pip install maturin

      - name: Install xmlgenerator
        run: uv run --no-project maturin develop --uv

      - name: Run tests
        run: uv run --no-project pytest -v
