name: Test Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup vcpkg libxml Cache
        if: contains(matrix.os, 'windows')
        uses: actions/cache@v3
        id: vcpkg-cache
        with:
          path: C:\vcpkg
          key: vcpkg-libxml2

      - name: Setup Environment (Act)
        if: ${{ env.ACT }}
        run: . .github/setup-act.sh

      - name: Setup Environment (Windows)
        if: contains(matrix.os, 'windows')
        run: . .github/setup-windows.ps1

      - name: UV setup
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      - name: Install Dependencies
        run: |
          uv sync --all-packages --all-groups

      - name: Lint with Ruff
        run: uv run ruff check

      - name: Run tests
        uses: nick-fields/retry@v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: uv run pytest -v

